### ISSUE TITLE
Retroactive 1.9 bug with Monterey 12.3.1

### ISSUE THREAD

**Issue by bobtennis** [cormiertyshawn895/cormiertyshawn895.github.io#1]
This is an issue I encountered with Retroactive 1.9 and Monterey 12.3.1.

You may already be aware of this, but when upgrading to Monterey 12.3.1 from Monterey 12.2, it "breaks" iPhoto. Aperture and iTunes still work. I originally installed Retroactive 1.9 when on Big Sur, and it still worked on migration to Monterey, but this latest Mac update "broke" the patch. I noticed this on 2 Macs, so not an isolated case.

When attempting to launch iPhoto, it generates an "iPhoto quit unexpectedly" message. Try it to see the report it generates if that helps, I did not understand a word of it!

Retroactive 1.9 is a fantastic program, I am grateful for your efforts. I hope you find the time to look into this recent issue.

Regards, 
Bob Brennan
bobbrennan@att.net

**Comment by cormiertyshawn895** [comment]
Thanks for your report! This is fixed in [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0).
